version: "3"

dotenv:
  - ".env.local"

tasks:
  default:
    cmds:
      - cargo run
  run:release:
    cmds:
      - cargo run --release
  delete:
    cmds:
      - cargo run --bin delete --release
